# XML output to test/errFailPassXmlQuiet-failures.xml
# Started on 03/21/16 23:00:56
# Starting class: TestAnotherThing
# Starting test: TestAnotherThing.testFail1
# Failure: test/test_with_err_fail_pass.lua:41: expected: 0, actual: 2
# Starting test: TestAnotherThing.testFail2
# Failure: test/test_with_err_fail_pass.lua:45: expected: 0, actual: 3
# Starting test: TestAnotherThing.testSuccess1
# Starting test: TestAnotherThing.testSuccess2
# Starting class: TestSomething
# Starting test: TestSomething.testFail1
# Failure: test/test_with_err_fail_pass.lua:15: expected: 0, actual: 2
# Starting test: TestSomething.testFail2
# Failure: test/test_with_err_fail_pass.lua:19: expected: 0, actual: 3
# Starting test: TestSomething.testSuccess1
# Starting test: TestSomething.testSuccess2
# Starting test: testFuncFail1
# Failure: test/test_with_err_fail_pass.lua:62: expected: 0, actual: 3
# Starting test: testFuncSuccess1
# Ran 10 tests in 0.001 seconds, 5 successes, 5 failures, 5 non-selected
