<testsuites>
    <testsuite name="TestFailuresWithXml">
        <testcase classname="TestFailuresWithXml"
            name="TestFailuresWithXml.test_failure_with_cdata_xml">
            <failure type="test/test_with_xml.lua:13: expected: &quot;got it&quot;
actual: &quot;cdata does not like ]]&gt;&quot;">
                <![CDATA[stack traceback:
	./luaunit.lua:473: in function 'assertEquals'
	test/test_with_xml.lua:13: in function 'TestFailuresWithXml.test_failure_with_cdata_xml'
	./luaunit.lua:1451: in function <./luaunit.lua:1451>
	[C]: in function 'xpcall'
	./luaunit.lua:1451: in function 'protectedCall'
	./luaunit.lua:1508: in function 'execOneFunction'
	./luaunit.lua:1607: in function 'runSuiteByInstances'
	./luaunit.lua:1660: in function 'runSuiteByNames'
	./luaunit.lua:1736: in function <./luaunit.lua:1676>
	(...tail calls...)
	test/test_with_xml.lua:17: in main chunk
	[C]: in ?]]></failure>
        </testcase>
        <testcase classname="TestFailuresWithXml"
            name="TestFailuresWithXml.test_failure_with_simple_xml">
            <failure type="test/test_with_xml.lua:9: expected: &quot;got it&quot;
actual: &apos;&lt;toto&gt;ti&quot;ti&lt;/toto&gt;&apos;">
                <![CDATA[stack traceback:
	./luaunit.lua:473: in function 'assertEquals'
	test/test_with_xml.lua:9: in function 'TestFailuresWithXml.test_failure_with_simple_xml'
	./luaunit.lua:1451: in function <./luaunit.lua:1451>
	[C]: in function 'xpcall'
	./luaunit.lua:1451: in function 'protectedCall'
	./luaunit.lua:1508: in function 'execOneFunction'
	./luaunit.lua:1607: in function 'runSuiteByInstances'
	./luaunit.lua:1660: in function 'runSuiteByNames'
	./luaunit.lua:1736: in function <./luaunit.lua:1676>
	(...tail calls...)
	test/test_with_xml.lua:17: in main chunk
	[C]: in ?]]></failure>
        </testcase>
    </testsuite>
</testsuites>
